In [1]:
import torch
import cupy as cp

torch.cuda.is_available()

True

# Inspect data

In [13]:
! head store/data.csv

0.233449,0.166667,0.381818,0.424594,0.164110,0.354839,0.250000,0.325581,0.166184,0.192771,6.000000
0.160279,0.196078,0.263636,0.262181,0.176380,0.161290,0.346154,0.255814,0.196453,0.301205,5.000000
0.083624,0.156863,0.300000,0.396752,0.191718,0.177419,0.355769,0.360465,0.226141,0.186747,6.000000
0.097561,0.107843,0.390909,0.201856,0.019939,0.451613,0.288462,0.372093,0.088490,0.216867,7.000000
0.073171,0.411765,0.445455,0.271462,0.007669,0.467742,0.413462,0.232558,0.128976,0.283133,5.000000
0.111498,0.235294,0.454545,0.197216,0.062883,0.822581,0.201923,0.406977,0.048775,0.168675,7.000000
0.024390,0.107843,0.309091,0.213457,0.015337,0.500000,0.442308,0.500000,0.132832,0.253012,4.000000
0.118467,0.127451,0.363636,0.262181,0.151840,0.419355,0.326923,0.209302,0.147869,0.186747,6.000000
0.108014,0.225490,0.290909,0.248260,0.185583,0.387097,0.298077,0.500000,0.159823,0.198795,6.000000
0.149826,0.137255,0.445455,0.357309,0.214724,0.096774,0.403846,0.546512,0.254290,0.253012,7.000000

## Parse data

In [14]:
import pandas as pd

df = pd.read_csv('store/data.csv', header=None)
df.columns = [ f'feat{i:1d}' for i in range(10) ] + ['label']
df = df.convert_dtypes()
df

         feat0     feat1     feat2  ...     feat8     feat9  label
0     0.233449  0.166667  0.381818  ...  0.166184  0.192771      6
1     0.160279  0.196078  0.263636  ...  0.196453  0.301205      5
2     0.083624  0.156863       0.3  ...  0.226141  0.186747      6
3     0.097561  0.107843  0.390909  ...   0.08849  0.216867      7
4     0.073171  0.411765  0.445455  ...  0.128976  0.283133      5
...        ...       ...       ...  ...       ...       ...    ...
3995  0.216028  0.098039  0.372727  ...  0.155966  0.144578      6
3996  0.202091  0.147059       0.4  ...  0.229227  0.210843      6
3997  0.111498  0.156863  0.727273  ...  0.144399  0.192771      5
3998  0.052265  0.215686  0.463636  ...  0.103913  0.162651      6
3999  0.216028  0.176471  0.427273  ...  0.164064   0.23494      6

[4000 rows x 11 columns]

In [15]:
df

         feat0     feat1     feat2  ...     feat8     feat9  label
0     0.233449  0.166667  0.381818  ...  0.166184  0.192771      6
1     0.160279  0.196078  0.263636  ...  0.196453  0.301205      5
2     0.083624  0.156863       0.3  ...  0.226141  0.186747      6
3     0.097561  0.107843  0.390909  ...   0.08849  0.216867      7
4     0.073171  0.411765  0.445455  ...  0.128976  0.283133      5
...        ...       ...       ...  ...       ...       ...    ...
3995  0.216028  0.098039  0.372727  ...  0.155966  0.144578      6
3996  0.202091  0.147059       0.4  ...  0.229227  0.210843      6
3997  0.111498  0.156863  0.727273  ...  0.144399  0.192771      5
3998  0.052265  0.215686  0.463636  ...  0.103913  0.162651      6
3999  0.216028  0.176471  0.427273  ...  0.164064   0.23494      6

[4000 rows x 11 columns]